/**
 * Design tokens: names, the contrast each pair must meet, and the CSS emitter.
 *
 * The values live in tokens.json, generated by scripts/brand/build-tokens.ts
 * from the colors extracted out of /brand. Nothing here holds a color: this
 * module only says which tokens exist and which pairs must be readable, so the
 * generator, the web app and the tests cannot drift apart.
 */
import type { ThemeMode } from './chart-palette.ts';

export const SEMANTIC_COLORS = [
  'background',
  'foreground',
  'heading',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'muted',
  'muted-foreground',
  'primary',
  'primary-foreground',
  'primary-hover',
  'secondary',
  'secondary-foreground',
  'accent',
  'accent-foreground',
  'accent-strong',
  'accent-strong-foreground',
  'border',
  'input',
  'ring',
  'link',
  'sidebar',
  'sidebar-foreground',
  'sidebar-muted-foreground',
  'sidebar-accent',
  'sidebar-border',
] as const;
export type SemanticColor = (typeof SEMANTIC_COLORS)[number];

/** Traffic-light tones. Each one always ships with an icon and a text label. */
export const STATUS_TONES = ['success', 'warning', 'danger', 'info', 'neutral'] as const;
export type StatusTone = (typeof STATUS_TONES)[number];

export const STATUS_PARTS = ['solid', 'solid-foreground', 'subtle', 'on-subtle', 'border'] as const;
export type StatusPart = (typeof STATUS_PARTS)[number];

export const RAMP_STEPS = [
  '50',
  '100',
  '200',
  '300',
  '400',
  '500',
  '600',
  '700',
  '800',
  '900',
  '950',
] as const;
export type RampStep = (typeof RAMP_STEPS)[number];

export interface ThemeTokens {
  colors: Record<SemanticColor, string>;
  status: Record<StatusTone, Record<StatusPart, string>>;
  chart: {
    surface: string;
    categorical: string[];
    sequential: string[];
  };
}

export interface BrandTokens {
  $comment: string;
  brand: { green: string; peach: string; salmon: string; blush: string };
  ramps: Record<'green' | 'accent' | 'neutral', Record<RampStep, string>>;
  themes: Record<ThemeMode, ThemeTokens>;
  typography: {
    display: { family: string; fallback: string };
    sans: { family: string; fallback: string };
    label: { textTransform: string; letterSpacing: string; fontWeight: number; fontSize: string };
  };
  radius: Record<'control' | 'card' | 'panel' | 'pill', string>;
  shadow: Record<'sm' | 'md' | 'lg', string>;
}

/** A token reference: a semantic color or `status.<tone>.<part>`. */
export type TokenRef = SemanticColor | `status.${StatusTone}.${StatusPart}`;

export interface ContrastRequirement {
  fg: TokenRef;
  bg: TokenRef;
  /** 4.5 for text, 3 for large text, icons and component boundaries (WCAG 2.2 AA). */
  min: number;
  use: string;
}

const TEXT = 4.5;
const NON_TEXT = 3;

/** Every pair the interface relies on. The tests check all of them in both themes. */
export const CONTRAST_REQUIREMENTS: readonly ContrastRequirement[] = [
  { fg: 'foreground', bg: 'background', min: TEXT, use: 'Texto principal sobre el fondo' },
  { fg: 'foreground', bg: 'card', min: TEXT, use: 'Texto principal en tarjetas' },
  { fg: 'foreground', bg: 'muted', min: TEXT, use: 'Texto sobre superficies tenues' },
  { fg: 'heading', bg: 'background', min: TEXT, use: 'Títulos sobre el fondo' },
  { fg: 'heading', bg: 'card', min: TEXT, use: 'Títulos en tarjetas' },
  { fg: 'card-foreground', bg: 'card', min: TEXT, use: 'Texto de tarjetas' },
  { fg: 'popover-foreground', bg: 'popover', min: TEXT, use: 'Menús y diálogos' },
  { fg: 'muted-foreground', bg: 'background', min: TEXT, use: 'Texto secundario sobre el fondo' },
  { fg: 'muted-foreground', bg: 'card', min: TEXT, use: 'Texto secundario en tarjetas' },
  { fg: 'muted-foreground', bg: 'muted', min: TEXT, use: 'Texto secundario en superficie tenue' },
  { fg: 'primary-foreground', bg: 'primary', min: TEXT, use: 'Botón primario' },
  {
    fg: 'primary-foreground',
    bg: 'primary-hover',
    min: TEXT,
    use: 'Botón primario al pasar el cursor',
  },
  { fg: 'secondary-foreground', bg: 'secondary', min: TEXT, use: 'Botón secundario' },
  { fg: 'accent-foreground', bg: 'accent', min: TEXT, use: 'Bloques destacados (rubor)' },
  { fg: 'accent-strong-foreground', bg: 'accent-strong', min: TEXT, use: 'Insignias en durazno' },
  { fg: 'link', bg: 'background', min: TEXT, use: 'Enlaces sobre el fondo' },
  { fg: 'link', bg: 'card', min: TEXT, use: 'Enlaces en tarjetas' },
  { fg: 'input', bg: 'card', min: NON_TEXT, use: 'Borde de campos (WCAG 1.4.11)' },
  { fg: 'input', bg: 'background', min: NON_TEXT, use: 'Borde de campos sobre el fondo' },
  { fg: 'ring', bg: 'background', min: NON_TEXT, use: 'Indicador de foco' },
  { fg: 'ring', bg: 'card', min: NON_TEXT, use: 'Indicador de foco en tarjetas' },
  { fg: 'primary', bg: 'background', min: NON_TEXT, use: 'Botón primario visible sobre el fondo' },
  { fg: 'primary', bg: 'card', min: NON_TEXT, use: 'Botón primario visible en tarjetas' },
  {
    fg: 'sidebar-foreground',
    bg: 'sidebar',
    min: TEXT,
    use: 'Navegación lateral y barra superior',
  },
  {
    fg: 'sidebar-muted-foreground',
    bg: 'sidebar',
    min: TEXT,
    use: 'Texto secundario en la navegación',
  },
  { fg: 'sidebar-accent', bg: 'sidebar', min: NON_TEXT, use: 'Marca de la sección activa' },
  ...STATUS_TONES.flatMap((tone): ContrastRequirement[] => [
    {
      fg: `status.${tone}.on-subtle`,
      bg: `status.${tone}.subtle`,
      min: TEXT,
      use: `Etiqueta de estado "${tone}"`,
    },
    {
      fg: `status.${tone}.solid-foreground`,
      bg: `status.${tone}.solid`,
      min: TEXT,
      use: `Texto sobre estado "${tone}" sólido`,
    },
    {
      fg: `status.${tone}.solid`,
      bg: 'card',
      min: NON_TEXT,
      use: `Icono de estado "${tone}" en tarjetas`,
    },
    {
      fg: `status.${tone}.on-subtle`,
      bg: 'card',
      min: TEXT,
      use: `Texto de estado "${tone}" en tarjetas`,
    },
  ]),
];

/** Resolves a token reference to its value in one theme. */
export function resolveToken(theme: ThemeTokens, ref: TokenRef): string {
  if (ref.startsWith('status.')) {
    const [, tone, part] = ref.split('.') as [string, StatusTone, StatusPart];
    return theme.status[tone][part];
  }
  return theme.colors[ref as SemanticColor];
}

// ---------------------------------------------------------------------------
// CSS
// ---------------------------------------------------------------------------

function themeDeclarations(theme: ThemeTokens, indent: string): string[] {
  const lines: string[] = [];
  for (const name of SEMANTIC_COLORS) lines.push(`${indent}--${name}: ${theme.colors[name]};`);
  for (const tone of STATUS_TONES) {
    for (const part of STATUS_PARTS) {
      lines.push(`${indent}--status-${tone}-${part}: ${theme.status[tone][part]};`);
    }
  }
  lines.push(`${indent}--chart-surface: ${theme.chart.surface};`);
  theme.chart.categorical.forEach((c, i) => lines.push(`${indent}--chart-${i + 1}: ${c};`));
  theme.chart.sequential.forEach((c, i) => lines.push(`${indent}--chart-seq-${i + 1}: ${c};`));
  return lines;
}

/**
 * The tokens as CSS custom properties. Dark values are declared twice: under
 * the OS preference (unless the user forced light) and under the explicit
 * data-theme toggle, which must win both ways.
 */
export function tokensToCss(t: BrandTokens): string {
  // Static constants carry a --brand- prefix so they never collide with
  // Tailwind's own --font-*, --radius-* and --shadow-* theme namespaces.
  const shared = [
    `  --brand-font-display: ${t.typography.display.family}, ${t.typography.display.fallback};`,
    `  --brand-font-sans: ${t.typography.sans.family}, ${t.typography.sans.fallback};`,
    ...Object.entries(t.radius).map(([k, v]) => `  --brand-radius-${k}: ${v};`),
    ...Object.entries(t.shadow).map(([k, v]) => `  --brand-shadow-${k}: ${v};`),
    ...(['green', 'accent', 'neutral'] as const).flatMap((ramp) =>
      RAMP_STEPS.map((step) => `  --brand-${ramp}-${step}: ${t.ramps[ramp][step]};`),
    ),
  ];
  return [
    '/* Generated by scripts/brand/build-tokens.ts from brand/palette.json. Do not edit by hand. */',
    ':root {',
    '  color-scheme: light;',
    ...shared,
    ...themeDeclarations(t.themes.light, '  '),
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    "  :root:where(:not([data-theme='light'])) {",
    '    color-scheme: dark;',
    ...themeDeclarations(t.themes.dark, '    '),
    '  }',
    '}',
    '',
    ":root[data-theme='dark'] {",
    '  color-scheme: dark;',
    ...themeDeclarations(t.themes.dark, '  '),
    '}',
    '',
  ].join('\n');
}
